### ISSUE TITLE
Running through NRPE

### ISSUE THREAD

**Issue by JonathanWilkins** [hobbyquaker/check_pm2#4]
Hi 

I'm trying check_pm2 through NRPE but I can't seem to get it to work. 
My first guess is that is it a permission issue. If I run it in the console it works fine.

This is the command in nrpe.cfg
command[check_pm2]=check_pm2 -P process1
Testing it using
/usr/local/nagios/libexec/check_nrpe -H 127.0.0.1 -c check_pm2
I get - NRPE: Unable to read output

I've changing permissions in the sudo config
nagios    ALL=(ALL)  NOPASSWD: /usr/lib/node_modules/check_pm2

Any suggestions would be great.

**Comment by hobbyquaker** [comment]
my config:

`/etc/nagios/nrpe.cfg`:
```
command[check_pm2]=sudo /usr/local/bin/check_pm2 -A
```

`/etc/sudoers`:
```
nagios ALL=(ALL) NOPASSWD: /usr/local/bin/check_pm2
```

I guess your path to check_pm2 in the sudoers is wrong?

**Comment by JonathanWilkins** [comment]
Was my config in the sudoers. Thanks
